# Generated by Django 3.2.12 on 2024-03-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i54m_apiuser', '0001_inital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_secret',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='app_id',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
